name: Expo Preview

on:
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm install -g eas-cli

      - name: Expo Preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas update --branch preview --message "Preview build"
