name: Monorepo Cache

on:
  push:
    branches: [ "main" ]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            app/package-lock.json
            admin/package-lock.json
            worker/package-lock.json
            modules/**/package-lock.json

      - name: Install root dependencies (no workspaces)
        run: npm install --workspaces=false
